name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze --no-fatal-infos

      - name: Build APK (Release)
        run: flutter build apk --release --split-per-abi

      - name: Build APK (Universal)
        run: flutter build apk --release

      - name: Rename APKs
        run: |
          mkdir -p build/outputs
          cp build/app/outputs/flutter-apk/app-release.apk build/outputs/IPTV-Editor-Pro-universal.apk
          cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk build/outputs/IPTV-Editor-Pro-arm64.apk || true
          cp build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk build/outputs/IPTV-Editor-Pro-arm32.apk || true
          cp build/app/outputs/flutter-apk/app-x86_64-release.apk build/outputs/IPTV-Editor-Pro-x86_64.apk || true

      - name: Upload APK Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: IPTV-Editor-Pro-APKs
          path: build/outputs/*.apk
          retention-days: 30

      - name: Create Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build/outputs/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
